/-
Copyright (c) 2026 Yunzhou Xie and contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yunzhou Xie, Yichen Feng, Jujian Zhang, Yael Dillies
-/

import LeanPool.BrauerGroupNew.Mathlib.Algebra.Algebra.Subalgebra.Lattice
import LeanPool.BrauerGroupNew.Subfield.Splitting
import Mathlib.FieldTheory.JacobsonNoether

/-!
# LeanPool.BrauerGroupNew.Subfield.Separable

Imported Lean Pool material for `LeanPool.BrauerGroupNew.Subfield.Separable`.
-/

universe u

variable (K D : Type u) [Field K] [DivisionRing D] [Algebra K D] [Algebra.IsCentral K D]
  [FiniteDimensional K D]

open Polynomial
omit [Algebra.IsCentral K D] [FiniteDimensional K D] in
lemma SubField.adjoin_centralizer_mul_comm (L : SubField K D) (a : D)
    (ha : a ∈ Subalgebra.centralizer K L) : ∀ (x y : D), x ∈ Algebra.adjoin K (L ∪ {a}) →
    y ∈ Algebra.adjoin K (L ∪ {a}) → x * y = y * x :=
  fun x y hx hy ↦ by
    rw [Algebra.mem_adjoin_iff] at hx hy
    rw [Subalgebra.mem_centralizer_iff] at ha
    refine Subring.closure_induction₂ (R := D) (fun x1 y1 hx1 hy1 ↦ by
      simp only [Set.mem_union, SetLike.mem_coe, Set.mem_singleton_iff, Set.mem_range] at hx1 hy1
      obtain hx11 | hx12 | hx13 := hx1
      all_goals obtain hy11 | hy12 | hy13 := hy1
      · obtain ⟨b, rfl⟩ := hx11
        obtain ⟨c, rfl⟩ := hy11
        exact Algebra.commutes b ((algebraMap K D) c)
      · obtain ⟨b, rfl⟩ := hx11
        exact Algebra.commutes b y1
      · obtain ⟨b, rfl⟩ := hx11
        subst hy13
        exact Algebra.commutes b y1
      · obtain ⟨b, rfl⟩ := hy11
        exact (Algebra.commutes b x1).symm
      · exact L.2 hx12 hy12
      · simp_all
      · subst hx13
        obtain ⟨b, rfl⟩ := hy11
        exact (Algebra.commutes b x1).symm
      · simp_all
      · simp_all) ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ ?_ hx hy
    all_goals try
      simp_all only [Set.union_singleton, Set.union_insert, zero_mul, mul_zero, one_mul, mul_one,
        neg_mul, mul_neg, add_mul, mul_add, forall_const, implies_true]
    · rintro x y z - - - hxz hyz
      rw [mul_assoc, hyz, ← mul_assoc, hxz, mul_assoc]
    · rintro x y z - - - hxy hxz
      rw [← mul_assoc, hxy, mul_assoc, hxz, ← mul_assoc]

/-- The commutative ring structure on the algebra generated by adjoining a centralizing element. -/
@[reducible]
def SubField.adjoinCommRing (L : SubField K D) (a : D) (ha : a ∈ Subalgebra.centralizer K L) :
    CommRing (Algebra.adjoin K (L ∪ {a})) where
  mul_comm := fun ⟨x, hx⟩ ⟨y, hy⟩ ↦ by
    ext
    simp [SubField.adjoin_centralizer_mul_comm K D L a ha x y hx hy]

instance SubField.adjoin_isDomain (L : SubField K D) (a : D) :
    IsDomain (Algebra.adjoin K (L ∪ {a})) where
  mul_left_cancel_of_ne_zero {x} hx y z eq := by
    simp_all
  mul_right_cancel_of_ne_zero {x} hx y z eq := by
    simp_all

/-- The subfield generated by a subfield and an element centralizing that subfield. -/
def SubField.adjoin (L : SubField K D) (a : D) (ha : a ∈ Subalgebra.centralizer K L) :
    SubField K D where
  __ := Algebra.adjoin K (L ∪ {a})
  algebraMap_mem' k := by
    simp_all
  mul_comm x y hx hy := by
    exact SubField.adjoin_centralizer_mul_comm K D L a ha x hx y hy
  exists_inverse x hx hx0 := by
    let := SubField.adjoinCommRing K D L a ha
    have := isField_of_isIntegral_of_isField' (R := K) (S := Algebra.adjoin K (L ∪ {a}))
      (Semifield.toIsField K)
    exact ⟨(this.3 (Subtype.coe_ne_coe.mp hx0 : (⟨x, hx⟩ : Algebra.adjoin K _) ≠ 0)).choose.1,
    ⟨(this.3 (Subtype.coe_ne_coe.mp hx0 : (⟨x, hx⟩ : Algebra.adjoin _ _) ≠ 0)).choose.2,
      haveI := (this.3 (Subtype.coe_ne_coe.mp hx0 : (⟨x, hx⟩ : Algebra.adjoin _ _) ≠ 0)).choose_spec
      (Submonoid.mk_eq_one (Algebra.adjoin _ _).toSubring.toSubmonoid).mp this⟩⟩

/-- The natural algebra structure over a subfield after adjoining a centralizing element. -/
noncomputable local instance IsLAlg (L : SubField K D) (a : D)
    (ha : a ∈ Subalgebra.centralizer K L) :
  Algebra L (SubField.adjoin K D L a ha) := RingHom.toAlgebra' (Subalgebra.inclusion <|
    Set.subset_union_left |>.trans Algebra.subset_adjoin).toRingHom fun ⟨x, hx⟩ ⟨y, hy⟩ ↦
    Subtype.ext_iff|>.2 <| SubField.adjoin_centralizer_mul_comm K D L a ha _ y
      (Subalgebra.inclusion _ (⟨x, hx⟩ : L)).2 hy

local instance SubField.adjoin_scalarTower (L : SubField K D) (a : D)
    (ha : a ∈ Subalgebra.centralizer K L) :
    IsScalarTower K L (SubField.adjoin K D L a ha) where
  smul_assoc k l x := Subtype.ext_iff.2 <| by
    change (k • (l : D)) * (x : D) = k • ((l : D) * (x : D))
    rw [smul_mul_assoc]

omit [Algebra.IsCentral K D] [FiniteDimensional K D] in
lemma SubField.le_centralizer (L : SubField K D) : L.toSubalgebra ≤ Subalgebra.centralizer _ L :=
  fun _ hx _ hy ↦ L.mul_comm hy hx

omit [Algebra.IsCentral K D] in
lemma SubField.adjoin_le_centralizer (L : SubField K D) (a : D)
    (ha : a ∈ Subalgebra.centralizer K L) :
    (SubField.adjoin K D L a ha).1 ≤ Subalgebra.centralizer K (A := D) L := by
  change Algebra.adjoin _ _ ≤ _
  rw [Algebra.adjoin_le_iff, Set.union_subset_iff, Set.singleton_subset_iff]
  exact ⟨SubField.le_centralizer _ _ _, ha⟩

/-- The set of subfields of a division algebra that are separable over the center. -/
abbrev AllSepSubfield : Set (SubField K D) :=
  { L : SubField K D | Algebra.IsSeparable K L }

instance : Nonempty (AllSepSubfield K D) :=
  ⟨⊥, by simpa using Algebra.IsSeparable.of_algHom K K <| Algebra.botEquiv K D⟩

/-- The supremum of a nonempty chain of separable subfields, as a separable subfield. -/
noncomputable abbrev iSupChainSepsubfield (c : Set (AllSepSubfield K D)) [Nonempty c]
    (hc1 : IsChain (· ≤ ·) c) : AllSepSubfield K D where
  val := {
    __ := (⨆ (L : c), L.1.1.1 : Subalgebra K D)
    mul_comm x hx y hy := by
      simp only [Subsemiring.coe_carrier_toSubmonoid, Subalgebra.coe_toSubsemiring,
        SetLike.mem_coe] at hx hy
      have := Subalgebra.coe_iSup_of_directed hc1.directed
      dsimp at this
      change x ∈ (_ : Set _) at hx
      change _ ∈ ( _ : Set _) at hy
      erw [this] at hx hy
      simp only [Set.mem_iUnion, SetLike.mem_coe] at hx hy
      obtain ⟨L1, hx⟩ := hx
      obtain ⟨L2, hy⟩ := hy
      obtain ⟨L3, hL31, hL32⟩ := hc1.directed L1 L2
      exact L3.1.1.mul_comm (hL31 hx) (hL32 hy)
    exists_inverse x hx hx0 := by
      simp only [Subalgebra.coe_toSubsemiring,
        Subsemiring.coe_carrier_toSubmonoid, SetLike.mem_coe] at *
      let : Nonempty c := Set.Nonempty.to_subtype (Set.Nonempty.of_subtype)
      have := Subalgebra.coe_iSup_of_directed hc1.directed
      dsimp at this
      change x ∈ (_ : Set _) at hx
      erw [this] at hx
      simp only [Set.mem_iUnion, SetLike.mem_coe] at hx
      obtain ⟨L1, hx⟩ := hx
      use L1.1.1.3 hx hx0|>.choose
      constructor
      · have : L1.1.1.1 ≤ ⨆ (L : c), (L.1.1).toSubalgebra := le_iSup_of_le L1 (by rfl)
        exact this (L1.1.1.3 hx hx0).choose_spec.1
      · exact L1.1.1.3 hx hx0|>.choose_spec.2
  }
  property := by
    simp only [Set.mem_ofPred_eq]
    rw [Algebra.isSeparable_def]
    simp only [Subtype.forall]
    intro a ha
    have := Subalgebra.coe_iSup_of_directed hc1.directed
    dsimp at this
    change a ∈ (_ : Set _) at ha
    erw [this] at ha
    simp only [Set.mem_iUnion, SetLike.mem_coe, Subtype.exists] at ha
    obtain ⟨L, ha', h, hL2⟩ := ha
    exact IsSeparable.map (F := K) (L := ((⨆ (L : c), L.1.1.1) : Subalgebra K D))
      (x := (⟨a, hL2⟩ : L))
      (Subalgebra.inclusion (le_iSup_of_le ⟨⟨L, ha'⟩, h⟩ le_rfl))
      (Subalgebra.inclusion_injective _) <| Algebra.isSeparable_def _ _|>.1 ha' ⟨a, hL2⟩

omit [Algebra.IsCentral K D] [FiniteDimensional K D] in
lemma exists_max_sepSub : ∃ L : AllSepSubfield K D, IsMax L :=
  zorn_le_nonempty (α := AllSepSubfield K D) fun c hc1 hc2 ↦ by
    have : Nonempty c := Set.Nonempty.to_subtype hc2
    use iSupChainSepsubfield K D c hc1
    change _ ∈ {L | _}
    simp only [Set.mem_ofPred_eq]
    intro L hL
    change L.1.1 ≤ (⨆ (L : c), L.1.1.1 : Subalgebra K D)
    exact le_iSup_of_le ⟨L, hL⟩ (by rfl)

theorem Set.centralizer.qsmul_mem (D : Type u) [DivisionRing D]
    (L : Set D) (q : ℚ) (a : D) (ha : a ∈ Set.centralizer L) :
    q • a ∈ Set.centralizer L := by
  rw [Set.mem_centralizer_iff] at ha ⊢
  intro m hm
  rw [Rat.smul_def]
  have (m : D) := Commute.left_comm <| Rat.cast_commute q m|>.symm
  rw [this, ha _ hm, mul_assoc]

instance (L : SubField K D) : DivInvMonoid (Subalgebra.centralizer K (A := D) L) where
  __ := (inferInstance : Monoid (Subalgebra.centralizer K (A := D) L))
  inv a := ⟨a⁻¹, Set.inv_mem_centralizer₀ a.2⟩
  div x y := ⟨(x / y : D), Set.div_mem_centralizer₀ x.2 y.2⟩
  div_eq_mul_inv x y := by ext; simp [← div_eq_mul_inv]; rfl

instance (L : SubField K D) : RatCast (Subalgebra.centralizer K (A := D) L) where
  ratCast q := ⟨q, Subalgebra.mem_centralizer_iff _|>.2 fun _ _↦ Rat.cast_commute _ _|>.symm⟩

omit [Algebra.IsCentral K D] [FiniteDimensional K D] in
@[simp]
lemma SubField.centralizer.coe_ratCast (L : SubField K D) (q : ℚ) :
    ((q : Subalgebra.centralizer K (A := D) L) : D) = q := rfl

instance (L : SubField K D) : NNRatCast (Subalgebra.centralizer K (A := D) L) where
  nnratCast q := ⟨q, Subalgebra.mem_centralizer_iff _|>.2 fun _ _ ↦ NNRat.cast_commute _ _|>.symm⟩

omit [Algebra.IsCentral K D] [FiniteDimensional K D] in
@[simp]
lemma SubField.centralizer.nnratCast_eq (L : SubField K D) (q : NNRat) :
    ((q : Subalgebra.centralizer K (A := D) L) : D) = q := rfl

instance centralizerSubfieldDiv (L : SubField K D) :
    DivisionRing (Subalgebra.centralizer K (A := D) L) where
  mul_inv_cancel a ha := by
    ext
    change (a : D) * (a : D)⁻¹ = 1
    exact mul_inv_cancel₀ (fun h ↦ ha (Subtype.ext h))
  inv_zero := by
    ext
    change ((0 : D)⁻¹) = 0
    simp
  ratCast_def q := by
    ext
    change (q : D) = (q.num : D) / (q.den : D)
    rw [Rat.cast_def]
  nnratCast q := ⟨q, Subalgebra.mem_centralizer_iff _|>.2 fun x _ ↦ NNRat.cast_commute _ _|>.symm⟩
  nnratCast_def q := by
    ext
    change (q : D) = (q.num : D) / (q.den : D)
    rw [NNRat.cast_def]
  qsmul q a := ⟨q • a.1, Set.centralizer.qsmul_mem D (L.1.1) q a.1 a.2⟩
  qsmul_def q x := by ext; simp [Rat.smul_def q x.1]
  nnqsmul q a := ⟨q.1 • a.1, Set.centralizer.qsmul_mem D L.1.1 q a.1 a.2⟩
  nnqsmul_def q a := by ext; simp [Rat.smul_def]

noncomputable instance (L : SubField K D) : Algebra L (Subalgebra.centralizer K (A := D) L) where
  smul l1 x := ⟨l1 * x, Set.mul_mem_centralizer
    (Subalgebra.mem_centralizer_iff K|>.2 fun _ hy ↦ L.2 l1.2 hy |>.symm) x.2⟩
  algebraMap := Subalgebra.inclusion (fun _ hx ↦ Subalgebra.mem_centralizer_iff K|>.2
    fun _ hy ↦ L.2 hx hy|>.symm : L.1 ≤ Subalgebra.centralizer K (A := D) L)
  commutes' l x := Subtype.ext_iff.2 <| Subalgebra.mem_centralizer_iff K|>.1 x.2 l.1 l.2
  smul_def' _ _ := rfl

instance (L : SubField K D) : IsScalarTower K L (Subalgebra.centralizer K (A := D) L) where
  smul_assoc k l x := Subtype.ext_iff.2 <| by
    change (k • (l : D)) * (x : D) = k • ((l : D) * (x : D))
    rw [smul_mul_assoc]

instance (L : SubField K D) : FiniteDimensional L (Subalgebra.centralizer K (A := D) L) :=
  haveI : FiniteDimensional K (Subalgebra.centralizer K (A := D) L) := inferInstance
  Module.Finite.of_restrictScalars_finite K _ _

/-- The center of a centralizer is equivalent to its image in the ambient division algebra. -/
noncomputable abbrev ZCLEquivZCLMap (L : SubField K D) :
    (Subalgebra.center K (Subalgebra.centralizer K (A := D) L)) ≃ₐ[K] Subalgebra.map
      (Subalgebra.centralizer K (A := D) L).val
      (Subalgebra.center K (Subalgebra.centralizer K (A := D) L)) :=
  AlgEquiv.ofBijective {
    toFun x := ⟨x.1, ⟨x.1, x.2, rfl⟩⟩
    map_one' := by ext; rfl
    map_mul' _ _ := by ext; simp
    map_zero' := by ext; rfl
    map_add' _ _ := by ext; simp
    commutes' _ := by ext; simp }
  ⟨fun x y eq ↦ by
      have eq' := congrArg Subtype.val eq
      change (x : D) = (y : D) at eq'
      apply Subtype.ext
      apply Subtype.ext
      exact eq',
    fun ⟨y, ⟨y', hy1, hy2⟩⟩ ↦ ⟨⟨y', hy1⟩, by
      apply Subtype.ext
      exact hy2⟩⟩

/-- The subfield generated by one element over the base field. -/
abbrev SubField.botAdjoin (a : D) : SubField K D :=
  SubField.adjoin K D ⊥ a (by
    rw [Subalgebra.mem_centralizer_iff];
    intro y (hy : y ∈ (Algebra.ofId _ _).range);
    obtain ⟨y, rfl⟩ := hy
    exact Algebra.commutes _ _)

omit [Algebra.IsCentral K D] in
@[simp]
lemma SubField.self_mem_botAdjoin (a : D) :
    a ∈ (SubField.botAdjoin K D a) := by
  apply Algebra.subset_adjoin
  simp

omit [Algebra.IsCentral K D] in
lemma SubField.botAdjoin_coe (a : D) :
    (SubField.botAdjoin K D a).1 = Algebra.adjoin K {a} := by
  apply le_antisymm
  · change Algebra.adjoin _ _ ≤ _
    rw [Algebra.adjoin_le_iff, Set.union_subset_iff]
    exact ⟨bot_le (α := Subalgebra K D), by simp⟩
  · rw [Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    simp

-- todo: replace mathlib version with this one
theorem IsSeparable.of_algHom_of_map
    {F : Type*} [Field F] {K : Type*} {E : Type*} [Field K] [Ring E]
  [Algebra F K] [Algebra F E] [Nontrivial E] (f : K →ₐ[F] E) {x : K}
  (h : IsSeparable F (f x)) : IsSeparable F x :=
  have ⟨_q, hq⟩ := minpoly.dvd F x (p := minpoly F (f x)) (by
    apply f.injective
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, map_zero, ← aeval_algHom_apply,
      minpoly.aeval])
  (Eq.mp (congrArg Separable hq) h).of_mul_left

open Subalgebra in
theorem exists_sep_masSubfield' : ∃ (a : D), IsMax (SubField.botAdjoin K D a) ∧
    Algebra.IsSeparable K (SubField.botAdjoin K D a) := by
  obtain ⟨L, hL⟩ := exists_max_sepSub K D
  let CL := Subalgebra.centralizer K (A := D) L
  suffices h : CL = L.1.1 by
    have Lmax := maxsubfield_of_div_iff K D L.1 |>.1 <|
      cor_two_2to3 K D L.1 (cor_two_1to2 K D L.1 |>.1 h)
    have : Algebra.IsSeparable _ _  := L.2
    obtain ⟨a, ha⟩ := Field.exists_primitive_element K L.1
    use a
    constructor
    · convert Lmax
      apply SubField.toSubalgebra_injective
      simp [SubField.botAdjoin_coe]
      have hmap := congrArg
        (fun E : IntermediateField K L.1 ↦ E.toSubalgebra.map L.1.toSubalgebra.val) ha
      simpa [IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic, AlgHom.map_adjoin,
        Set.image_singleton, Subalgebra.range_val] using hmap
    · exact Algebra.IsSeparable.of_algHom K (E := (SubField.botAdjoin K D a.1)) L.1 <|
        Subalgebra.inclusion (by
          rw [SubField.botAdjoin_coe K D a.1, Algebra.adjoin_le_iff]
          simp)
  by_contra! h
  let ZCL := Subalgebra.center K CL
  let CCL := Subalgebra.centralizer K (A := D) CL
  let : Field L.1 := inferInstance
  have sim : IsSimpleRing L.1.1 := inferInstance
  have eq1 := double_centralizer (F := K) (A := D) L.1.1
  change CCL = L.1.1 at eq1
  have eq2 : CCL = ZCL.map (Subalgebra.val _) := by
    dsimp [CCL, ZCL, CL] at *
    refine le_antisymm ?_ ?_
    · rw [eq1]
      intro x hx
      simp only [mem_map, coe_val, Subtype.exists, exists_and_right, exists_eq_right]
      constructor
      · rw [Subalgebra.mem_center_iff]
        intro y
        ext
        have hy := y.2
        rw [Subalgebra.mem_centralizer_iff] at hy
        exact hy x hx |>.symm
      · rw [Subalgebra.mem_centralizer_iff]
        exact fun y hy ↦ L.1.2 hy hx
    · convert le_trans ?_
        (Subalgebra.map_centralizer_le_centralizer_image ⊤ (centralizer K (L.1.1 : Set D)).val)
      · simp
      simp_all
    -- rw [eq1]
  rw [eq1] at eq2
  have inst1 : Algebra.IsAlgebraic L CL := Algebra.IsAlgebraic.of_finite L CL
  have inst2 : FiniteDimensional ZCL CL := inferInstance
  have inst3: Algebra.IsAlgebraic ZCL CL := Algebra.IsAlgebraic.of_finite ZCL CL
  have ass : Subring.center ↥CL ≠ ⊤ := by
    rw [eq2] at h
    symm
    contrapose! h
    apply Subalgebra.toSubring_injective
    convert congr(Subring.map CL.val.toRingHom $h)
    all_goals first
      | rfl
      | exact (Subalgebra.center_toSubring K ↥CL).symm
      | · ext x
          simp only [Subalgebra.mem_toSubring, Subring.mem_map, Subring.mem_top,
            true_and, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, Subalgebra.coe_val,
            Subtype.exists, exists_prop, exists_eq_right]
  obtain ⟨a, ha1, ha2⟩ := @JacobsonNoether.exists_separable_and_not_isCentral
    (Subalgebra.centralizer K (A := D) L) _ inst3 ass
  obtain ⟨L, hLsep⟩ := L
  have ha1_aux : a.1 ∉ L := by
    by_contra! haa
    have : a ∈ Subring.center (centralizer K L) := by
      rw [Subring.mem_center_iff]
      intro ⟨b, hb⟩
      rw [Subalgebra.mem_centralizer_iff] at hb
      ext
      simp [hb a.1 haa]
    tauto
  have cond3 : L ≠ SubField.adjoin K D L a.1 a.2 := by
    by_contra! eq
    obtain eq' := (SetLike.ext_iff.1 eq) a.1 |>.2 (Algebra.subset_adjoin <| by simp)
    tauto
  simp_all only
  let e1 := Subalgebra.equivOfEq L.1 _ eq2
  let e2 := ZCLEquivZCLMap K D L
  have asep := IsSeparable.of_equiv_equiv
    (A₁ := Subalgebra.center K (Subalgebra.centralizer K (A := D) L))
    (A₂ := L) (e2.trans e1.symm).toRingEquiv (RingEquiv.refl _) (by
    ext x
    simp only [AlgEquiv.toRingEquiv_toRingHom, RingHom.coe_comp, RingHom.coe_coe,
      Function.comp_apply, RingEquiv.coe_ringHom_refl, RingHomCompTriple.comp_eq,
      SetLike.coe_eq_coe]
    unfold e1 e2
    simp only [equivOfEq_symm]
    erw [AlgEquiv.trans_apply]
    apply Subtype.ext
    rfl) ha2
  have cond1 : Algebra.IsSeparable K (SubField.adjoin K D L a.1 a.2) := by
    rw [Algebra.isSeparable_def]
    rintro ⟨x, hx⟩
    change x ∈ Algebra.adjoin _ _  at hx
    refine Algebra.adjoin_induction (by
      intro x1 hx1
      simp only [Set.mem_union, SetLike.mem_coe, Set.mem_singleton_iff] at hx1
      obtain hxL | hxa := hx1
      · exact IsSeparable.map (F := K) (K := L)
          (L := SubField.adjoin K D L a.1 a.2) (x := (⟨x1, hxL⟩ : L))
          (Subalgebra.inclusion (Set.subset_union_left |>.trans Algebra.subset_adjoin))
          (Subalgebra.inclusion_injective _) <|
          (Algebra.isSeparable_def K L).1 hLsep ⟨x1, hxL⟩
      · subst hxa
        let : Algebra.IsSeparable K L := hLsep
        let := IsLAlg K D L a.1 a.2
        let := SubField.adjoin_scalarTower K D L a.1 a.2
        exact IsSeparable.of_algebra_isSeparable_of_isSeparable K (E := L)
          (K := SubField.adjoin K D L a.1 a.2)
          (x := ⟨a.1, Algebra.subset_adjoin (by simp)⟩) <| by
            let f : SubField.adjoin K D L a.1 a.2 →ₐ[L] centralizer K (L : Set D) :=
              ⟨(Subalgebra.inclusion
                (SubField.adjoin_le_centralizer K D L a.1 a.2)).toRingHom, fun r ↦ rfl⟩
            refine IsSeparable.of_algHom_of_map f asep
      )
      (fun k ↦ IsSeparable.map (Algebra.ofId K _) (FaithfulSMul.algebraMap_injective _ _)
        (Algebra.IsSeparable.isSeparable' k))
      (fun _ _ _ _ ↦ Field.isSeparable_add) (fun _ _ _ _ ↦ Field.isSeparable_mul)  hx
  have : (SubField.adjoin K D L a.1 a.2) ∈ AllSepSubfield K D := by
    simp [cond1]
  have cond2 : L ≤ SubField.adjoin K D L a.1 a.2 :=
    Set.subset_union_left (s := L.1) (t := {a.1}) |>.trans <| Algebra.subset_adjoin (R := K)
  change ∀ M : AllSepSubfield K D, (⟨L, hLsep⟩ : AllSepSubfield K D) ≤ M →
    M ≤ ⟨L, hLsep⟩ at hL
  specialize hL ⟨SubField.adjoin K D L a.1 a.2, cond1⟩ cond2
  have : L = SubField.adjoin K D L a.1 a.2 := le_antisymm cond2 hL
  tauto

theorem exists_sep_masSubfield : ∃ L : SubField K D, IsMax L ∧ Algebra.IsSeparable K L := by
  obtain ⟨a, hL1, hL2⟩ := exists_sep_masSubfield' K D
  exact ⟨SubField.botAdjoin K D a, hL1, hL2⟩

theorem exists_sep_splitting :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (_ : FiniteDimensional K L),
    Algebra.IsSeparable K L ∧ isSplit K D L := by
  obtain ⟨L, hL1, hL2⟩ := exists_sep_masSubfield K D
  exact ⟨L, inferInstance, inferInstance, inferInstance, hL2, isSplit_of_isMax K D L hL1⟩

omit [DivisionRing D] [Algebra K D] [Algebra.IsCentral K D] [FiniteDimensional K D] in
private theorem algHom_fieldRange_isSeparable {L Kbar : Type u} [Field L] [Field Kbar]
    [Algebra K L] [Algebra K Kbar] [Algebra.IsSeparable K L] (f : L →ₐ[K] Kbar) :
    Algebra.IsSeparable K f.fieldRange :=
  Algebra.IsSeparable.of_equiv_equiv (B₁ := L) (B₂ := f.fieldRange) (RingEquiv.refl K)
    (AlgEquiv.ofInjectiveField f).toRingEquiv <| by
      ext
      erw [AlgEquiv.ofInjective_apply _ f.injective]
      simp

omit [DivisionRing D] [Algebra K D] [Algebra.IsCentral K D] [FiniteDimensional K D] in
private theorem normalClosure_isSeparable {Kbar : Type u} [Field Kbar]
    [Algebra K Kbar] (L : Type u) [Field L] [Algebra K L]
    [Algebra.IsSeparable K L] :
    Algebra.IsSeparable K (IntermediateField.normalClosure K L Kbar) := by
  have : ∀ f : L →ₐ[K] Kbar, Algebra.IsSeparable K f.fieldRange := fun f ↦
    algHom_fieldRange_isSeparable (K := K) (L := L) (Kbar := Kbar) f
  rw [normalClosure_def]
  infer_instance

theorem exists_finite_galois_split :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (_ : FiniteDimensional K L),
    IsGalois K L ∧ isSplit K D L := by
  obtain ⟨L, _, _, _, hL1, hL2⟩ := exists_sep_splitting K D
  have : FiniteDimensional K L := inferInstance
  let K_bar := AlgebraicClosure K
  have : IsAlgClosed K_bar := inferInstance
  have : Algebra.IsAlgebraic K L := inferInstance
  let L' := IntermediateField.normalClosure K L K_bar
  let f := normalClosure.algHomEquiv K L K_bar |>.symm IsAlgClosed.lift
  let : Algebra.IsSeparable K L := hL1
  let : Algebra L L' := RingHom.toAlgebra f
  have : IsScalarTower K L L' := {
    smul_assoc k l x := by
      simp only [Algebra.smul_def, map_mul]
      rw [mul_assoc]
      congr 1
      change (normalClosure.algHomEquiv K L K_bar |>.symm IsAlgClosed.lift) _ = _
      simp only [AlgHom.commutes]
      rfl }
  have : Algebra.IsSeparable K L' := by
    simpa [L'] using normalClosure_isSeparable (K := K) (Kbar := K_bar) L
  have : IsGalois K L' := {
    to_isSeparable := inferInstance
    to_normal := inferInstance }
  have hsplit : isSplit K D L' := extensionOverSplit' K K_bar D L L' hL2
  exact ⟨L', inferInstance, inferInstance, inferInstance, inferInstance, hsplit⟩
